name: BuildExamplesLinux

on:
  [push, pull_request]

jobs:
  ubuntu_build_tests:
    name: Build Examples (Linux)
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build Samples
      run: |
        mkdir build
        cd build
        cmake -DVCG_BUILD_EXAMPLES=ON ..
        make -j4
