#ifndef SOCKETBASE_H
#define SOCKETBASE_H


#define SOCKET_PORT 8000
#define SOCKET_IP "127.0.0.1"
#define SOCKET_CMD_HEARTBEAT "SOCKET_CMD_HEARTBEAT"
#define SOCKET_CMD_SEND_FILE "SOCKET_CMD_SEND_FILE"
#define SOCKET_CMD_SELECT_PRINT_DISPLAY "SOCKET_CMD_SELECT_PRINT_DISPLAY"
#define SOCKET_CMD_LOGIN_INIT "SOCKET_CMD_LOGIN_INIT"
#define SOCKET_CMD_LOGIN_WIDGET_DISPLAY "SOCKET_CMD_LOGIN_WIDGET_DISPLAY"
#define SOCKET_CMD_CLOSE_NETWORK_PROCESS "SOCKET_CMD_CLOSE_NETWORK_PROCESS"
#define SOCKET_CMD_SELECT_FROM_UPDATE "SOCKET_CMD_SELECT_FROM_UPDATE"
#define SOCKET_CMD_AUTO_SELECT_FROM_UPDATE "SOCKET_CMD_AUTO_SELECT_FROM_UPDATE"
#define SOCKET_CMD_DEVICELIST_WIDGET_DISPLAY "SOCKET_CMD_DEVICELIST_WIDGET_DISPLAY"
#define SOCKET_CMD_PRINT_CTRL_WIDGET_DISPLAY "SOCKET_CMD_PRINT_CTRL_WIDGET_DISPLAY"
#define SOCKET_CMD_ANKERMAKE_WIDGET_DISPLAY "SOCKET_CMD_ANKERMAKE_WIDGET_DISPLAY"

#endif
